<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>config</string>
            <string>cfg</string>
        </array>
        <key>name</key>
        <string>Cisco</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^\s*no</string>
                <key>name</key>
                <string>invalid.illegal.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>crypto </string>
                <key>name</key>
                <string>string.unquoted.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>any</string>
                <key>name</key>
                <string>string.unquoted.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\$</string>
                <key>name</key>
                <string>constant.language.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>deny </string>
                <key>name</key>
                <string>support.constant.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>permit </string>
                <key>name</key>
                <string>constant.character.escape.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>object-group</string>
                <key>name</key>
                <string>markup.list.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>object</string>
                <key>name</key>
                <string>markup.list.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>host</string>
                <key>name</key>
                <string>markup.list.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^[\s]*!(.*)</string>
                <key>name</key>
                <string>comment.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>static</string>
                <key>name</key>
                <string>constant.numeric.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>tunnel-group</string>
                <key>name</key>
                <string>support.class.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>crypto</string>
                <key>name</key>
                <string>support.class.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
                <key>name</key>
                <string>work.numbers.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
                <key>name</key>
                <string>work.numbers.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*>(.*)</string>
                <key>name</key>
                <string>work.subcategory.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>### (.*)</string>
                <key>name</key>
                <string>work.maincategory.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*shutdown</string>
                <key>name</key>
                <string>cisco.shutdown.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*(snmp-server|ntp|ntp server|aaa|tacacs-server|logging|radius-server|ip name-server|ip domain-name|ip tacacs|rmon)</string>
                <key>name</key>
                <string>cisco.management.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^route-map|access-list|ip access-list</string>
                <key>name</key>
                <string>cisco.acl.routemap.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*interface.*|^\s*Interface.*|^\s*Int.*|^\s*int.*</string>
                <key>name</key>
                <string>cisco.interface.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>((FastEthernet|GigabitEthernet|TenGigabitEthernet|Ethernet|Fa|Gi|Te|eth|Eth|Et|et)\d+/\d?/*\d*|(Port-channel|port-channel|FastEthernet|Vlan|Po|VL|mgmt*|lo0*|lo1*|Et)\d+)</string>
                <key>name</key>
                <string>cisco.interface.sub.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(Loopback*|loopback*| eth-\d+\-\d+\-\d+| eth-\d*\-\d+| eth\d* | et-*| et\d+\-\d+|eth\d+\-\d+| v\d+|-v\d+|mgmt*|\|_|Eth\d+\d+)</string>
                <key>name</key>
                <string>cisco.interface.sub.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(router ospf|router bgp|router eigrp)(.*)</string>
                <key>name</key>
                <string>cisco.routing.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(description|desc) (.*)</string>
                <key>name</key>
                <string>cisco.description.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>!!!(.*)</string>
                <key>name</key>
                <string>cisco.note.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>---------------------------------------------------------------------------------------------------</string>
                <key>name</key>
                <string>work.divider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>###################################################################################################</string>
                <key>name</key>
                <string>work.maindivider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(physical|virtual)</string>
                <key>name</key>
                <string>cisco.management.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\w\w\d\d\w\w\d\w\d+</string>
                <key>name</key>
                <string>cisco.hostname.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\w\w\d\d\w\w\w\w\d+</string>
                <key>name</key>
                <string>cisco.hostname.ciscooo</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>text.ciscooo</string>
        <key>uuid</key>
        <string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
    </dict>
</plist>