<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>config</string>
            <string>cfg</string>
        </array>
        <key>name</key>
        <string>Cisco</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^\s*no</string>
                <key>name</key>
                <string>invalid.illegal.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>crypto|any</string>
                <key>name</key>
                <string>string.unquoted.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\$</string>
                <key>name</key>
                <string>constant.language.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>deny </string>
                <key>name</key>
                <string>support.constant.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>permit </string>
                <key>name</key>
                <string>constant.character.escape.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>object-group|object|host</string>
                <key>name</key>
                <string>markup.list.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^[\s]*!(.*)</string>
                <key>name</key>
                <string>comment.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>static</string>
                <key>name</key>
                <string>constant.numeric.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>tunnel-group</string>
                <key>name</key>
                <string>support.class.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
                <key>name</key>
                <string>work.numbers.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
                <key>name</key>
                <string>work.numbers.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*>(.*)</string>
                <key>name</key>
                <string>work.subcategory.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>### (.*)</string>
                <key>name</key>
                <string>work.maincategory.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*shutdown</string>
                <key>name</key>
                <string>cisco.shutdown.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*(snmp-server|ntp|ntp server|aaa|tacacs-server|logging|radius-server|ip name-server|ip domain-name|ip tacacs|rmon)</string>
                <key>name</key>
                <string>cisco.management.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^route-map|access-list|ip access-list</string>
                <key>name</key>
                <string>cisco.acl.routemap.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*interface.*|^\s*Interface.*|^\s*Int\b|^\s*int\b</string>
                <key>name</key>
                <string>cisco.interface.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>((FastEthernet|GigabitEthernet|TenGigabitEthernet|Ethernet|Fa|Gi|Te|eth|Eth|Et|et)\d+/\d?/*\d*|(Port-channel|port-channel|FastEthernet|Vlan|Po|Vl|mgmt*|lo0*|lo1*|Et|Lo*)\d+)</string>
                <key>name</key>
                <string>cisco.interface.sub.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(Loopback*|loopback*| eth-\d+\-\d+\-\d+| eth-\d*\-\d+| eth\d* | et-*| et\d+\-\d+|eth\d+\-\d+| v\d+|-v\d+|mgmt*|\|_|Eth\d+\d+)</string>
                <key>name</key>
                <string>cisco.interface.sub.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(router ospf|router bgp|router eigrp)(.*)</string>
                <key>name</key>
                <string>cisco.routing.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(description|desc) (.*)</string>
                <key>name</key>
                <string>cisco.description.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>!!!(.*)</string>
                <key>name</key>
                <string>cisco.note.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>---------------------------------------------------------------------------------------------------</string>
                <key>name</key>
                <string>work.divider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>###################################################################################################</string>
                <key>name</key>
                <string>work.maindivider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(=====.*)</string>
                <key>name</key>
                <string>cisco.discriminator.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\w\w\w-\w\w-\w+\d*-(\w+-?)*\d+(#|>)?)|AZRH57\d/.*</string>
                <key>name</key>
                <string>cisco.hostname.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(|crc|admin\sdown|\sdeny\s|\sdown\s|administratively\sdown|"no\sip\saddress|deny\sip\sany\sany|Null0|OFF\s|DOWN\s|block|Total output drops: [1-9]+|[1-9]+\sinput\serrors|[1-9]+\soutput\serrors|[1-9]+\sCRC|[1-9]+\sframe|[1-9]+\soverrun|[1-9]+\signored|[1-9]+\scollisions|Up\s->\sDown|(-)?half|Half)</string>
                <key>name</key>
                <string>cisco.reds.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(no\ssh|no\sshut|no\sshutdown|\spermit|\spass\s|\stransmit|up,\s|\sup\s|\sON\s|\sUP\s|ip\saddress|permit\sip\sany\sany|\sin\s|\swr\s|full|Full-duplex|Full\sDuplex|FULL|0 input errors|0 output errors|Total output drops: 0|Down\s->\sUp)</string>
                <key>name</key>
                <string>cisco.greens.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^T:.*</string>
                <key>name</key>
                <string>cisco.Tsdanc.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^S:.*</string>
                <key>name</key>
                <string>cisco.tSdanc.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^D:.*</string>
                <key>name</key>
                <string>cisco.tsDanc.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^A:.*</string>
                <key>name</key>
                <string>cisco.tsdAnc.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^N:.*</string>
                <key>name</key>
                <string>cisco.tsdaNc.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(^C:.*)|=====.*</string>
                <key>name</key>
                <string>cisco.tsdanC.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>[0-9]{2}/[0-9]{2}/[0-9]{4}\s[0-9]{2}:[0-9]{2}:[0-9]{2}.*</string>
                <key>name</key>
                <string>cisco.Expedio_entry.ciscooo</string>
            </dict>  
            <dict>
                <key>match</key>
                <string>([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9A-Fa-f]{4}[\.]){2}([0-9A-Fa-f]{4})</string>
                <key>name</key>
                <string>cisco.MAC.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d\d\s\d\d:\d\d:\d\d.\d+(?=(.*BGP-5-ADJCHANGE.*Up))</string>
                <key>name</key>
                <string>cisco.BGP_up_TS.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d\d\s\d\d:\d\d:\d\d.\d+(?=(.*BGP-5-ADJCHANGE.*Down))</string>
                <key>name</key>
                <string>cisco.BGP_down_TS.ciscooo</string>
            </dict>  
            <dict>
                <key>match</key>
                <string>.*admin\sdown.*down.*|.*administratively down down.*|(.*(0         ){8}0)|.*%SSH-.*|.*%SEC-SW1-6.*|PACKET|.*%SEC_LOGIN.*|.*%SEC_LOGOUT.*|.*%SNMP-SW1-3-AUTHFAIL.*|.*with note = Urgency: null .*|with note = |WARNING! :Thanks for Your Update.Since the BT Incident.*|asd\s*v|.*%SEC-6-IPACCESSLOGP.*</string>
                <key>name</key>
                <string>cisco.non_relevant.ciscooo</string>
            </dict>
            <dict>
                <key>match</key>
                <string>INC\d\d\d\d\d\d\d</string>
                <key>name</key>
                <string>cisco.inc.ciscooo</string>
            </dict> 
            <dict>
                <key>match</key>
                <string>(User:(acs|ACS)-.*logged command:)</string>
                <key>name</key>
                <string>cisco.LOG_command.ciscooo</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>text.ciscooo</string>
        <key>uuid</key>
        <string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
    </dict>
</plist>
