<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>w</string>
        </array>
        <key>name</key>
        <string>Work</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^\s*> (.*)</string>
                <key>name</key>
                <string>work.subcategory.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*### (.*)</string>
                <key>name</key>
                <string>work.maincategory.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>‾</string>
                <key>name</key>
                <string>work.divider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*________________________________________________________________________________________________________________________________________________</string>
                <key>name</key>
                <string>work.divider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*------------------------------------------------------------------------------------------------------------------------------------------------</string>
                <key>name</key>
                <string>work.divider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*################################################################################################################################################</string>
                <key>name</key>
                <string>work.maindivider.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
                <key>name</key>
                <string>work.numbers.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*!!!!(.*)</string>
                <key>name</key>
                <string>work.prio1.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*!!!(.*)</string>
                <key>name</key>
                <string>work.prio2.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*!!(.*)</string>
                <key>name</key>
                <string>work.prio3.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*!(.*)</string>
                <key>name</key>
                <string>work.prio4.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
                <key>name</key>
                <string>work.numbers.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^s*×(.*)</string>
                <key>name</key>
                <string>work.completed.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^s*¤(.*)</string>
                <key>name</key>
                <string>work.list.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\s\s\|\_\s)</string>
                <key>name</key>
                <string>work.listsub.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>((^(\-\s?))|(^(\s\-\s?))|(\||)|(|:)|([\[\]])|([\(\)]))</string>
                <key>name</key>
                <string>work.misc.work</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\w\w\w-\w\w-\w+\d*-(\w+-?)*\d+(#|>)?</string>
                <key>name</key>
                <string>cisco.hostname.ciscooo</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>text.work</string>
        <key>uuid</key>
        <string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
    </dict>
</plist>
